rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
#  - ruby-head
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
gemfile: 
  - ./Gemfile
  - ./Gemfile.net-ldap-0.4.0
notifications:
  recipients:
    - kou@cozmixng.org
before_install:
  - travis/before_install.sh
before_script:
  - travis/before_script.sh
